AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: PDF to text Lambda

Resources:
  pdftotxt:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      MemorySize: 512
      Timeout: 900
      Role: arn:aws:iam::346481752143:role/lambda_s3

      Environment:
        Variables:
          TARGET_BUCKET: aws-content-store-s3-bucket-346481752143-us-east-1-an

      Layers:
        - arn:aws:lambda:ap-northeast-1:844028273225:layer:tika:1

      Events:
        S3UploadTrigger:
          Type: S3
          Properties:
            Bucket: aws-pdf-source
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .pdf
