AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: PDF to text Lambda

Resources:
  pdftotxt:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      MemorySize: 512
      Timeout: 900
      Policies:
        - S3ReadPolicy:
            BucketName: aws-pdf-source
        - S3WritePolicy:
            BucketName: aws-content-store-s3-bucket-346481752143-us-east-1-an

      Environment:
        Variables:
          TARGET_BUCKET: aws-content-store-s3-bucket-346481752143-us-east-1-an
